[tool.black]
line-length = 100
target-version = ["py312"]
extend-exclude = """
(
    /migrations
)
"""

[tool.tox]
legacy_tox_ini = """
    [tox]
    envlist = flake8,black,py312
    skipsdist = true

    [testenv]
    basepython = python3.12

    [testenv:flake8]
    deps = flake8
    skip_install = true
    commands = flake8 --extend-exclude=migrations/,venv/ --max-line-length 100

    [testenv:black]
    deps = black
    skip_install = true
    commands = black .

    [testenv:py312]
    deps = 
        flask
        flask-sqlalchemy
        flask-login
        wtforms
        flask-wtf
        flask-bcrypt
        flask-migrate
        pyserial
        turbo-flask
        pytest>=7
        pytest-sugar
    commands = pytest -s -v
"""
