"""initial migration

Revision ID: 7c24d88098c4
Revises: 
Create Date: 2025-04-30 15:19:22.172525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c24d88098c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operational_time')
    op.drop_table('_alembic_tmp_nodes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_nodes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('battery_lvl', sa.INTEGER(), nullable=False),
    sa.Column('ldr_res', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operational_time',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('on_time', sa.DATETIME(), nullable=True),
    sa.Column('off_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
