"""Initial migration

Revision ID: 82dcd8672586
Revises: 
Create Date: 2025-01-29 23:53:52.325321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82dcd8672586'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('battery_lvl', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ldr_res', sa.Integer(), nullable=False))
        batch_op.drop_column('mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.VARCHAR(length=5), nullable=False))
        batch_op.drop_column('ldr_res')
        batch_op.drop_column('battery_lvl')

    # ### end Alembic commands ###
